apiVersion: v1 # Mandatory
kind: Pod # Mandatory
metadata: # Information under - does not control how pod behaves.
  name: db
  labels:
    type: db
    vendor: MongoLabs
spec:
  containers: # We can define more than one containers.
    - name: db
      image: mongo:3.3
      command: ["mongod"] # Command that should be executed when the container starts.
      args: ["--rest", "--httpinterface"] #Set of arguments.s

# Command to create the Pod.
# kuebctl create -f db.yml
# kubectl get pods -o wide
# kubectl get pods -o json
# kubectl get pods - yaml
# kubectl describe pod db  or kubectl describe -f db.yml

# ----------------------------------------------------------------
# Executing a new process inside the pods container.
# kubectl exec db ps aux
# Since this pod contains only one container we don't need to' specify the container no , we can specify with "-c" which container should be used .

# ----------------------------------------------------------------
# Running a interactive shell inside the pods container .
# kubectl exec -it db
# To get out of the container.
#  "exit"
# ----------------------------------------------------------------

# Getting Logs .
# ----------------------------------------------------------------
# kubectl logs db

