apiVersion: v1
kind: Pod
metadata:
  name: go-demo
  labels:
    type: stack
spec:
  containers:
    - name: db
      image: mongo:3.3
    - name: api
      image: vfarcic/go-demo-2
      env:
        - name: DB
          value: localhost

# --------------------------------------------------------------
# Kubectl run the file.

# kubectl create -f go_demo.yml
# kubectl get -f go_demo.yml
# kubectl get -f go_demo.yml -o json
# kubectl get -f /go_demo.yml \
# -o jsonpath="{.spec.containers[*].name}"

# --------------------------------------------------------------
# Executing Commands Inside The Pod .

# kubectl exec -it -c db go-demo ps aux

# --------------------------------------------------------------
# Logs From A Container .

# kubectl logs go-demo -c db
